## Spring REST
server:
    port: 8088

#Eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    

## MySQL
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
    application:
        name: course-service
    datasource:
        url: jdbc:mysql://localhost:3306/course_db
        username: aman_developer
        password: Am@n1998
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#looger
logging:
    level: 
        root: WARN
        com.cg: INFO