## Spring REST
server:
    port: 8083

#Eureka
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

## MySQL
spring:
    application:
        name: student-user-service
#looger
logging:
    level: 
        root: WARN
        com.cg: INFO