spring:
    profiles:
        active: prod

management:
    endpoints:
        web:
            exposure:
                include: '*'
            basePath: '/'
# HEALTH ENDPOINT
    endpoint:
        health:
            show-details: ALWAYS


# INFO ENDPOINT CONFIGURATION
info:
    app:
        name: '@project.name@'
        description: '@project.description@'
        version: '@project.version@'
        encoding: '@project.build.sourceEncoding@'
        java.version: '@java.version@'